### ISSUE TITLE
Missing class

### ISSUE THREAD

**Issue by TeoTN** [rkubosz/dyplompwr#1]
W readme brakuje informacji o tym, że wymagana jest klasa `mwrep.cls` z pakietu `mwcls`. Nie jest również jasne na jakiej wysokości względem plików pobieranych w postaci zipa powinna się znajdować praca.

**Comment by rkubosz** [comment]
Dodałem informację nt wymaganej klasy `mwrep` oraz trochę zmodyfikowałem opis instalacji pakietu. Otrzymany, po rozpakowaniu zipa, katalog `dyplompwr` powinien być umieszczony w tym samym katalogu (tzn na tej samej wysokości), co główny plik `*.tex` pracy dyplomowej. Można go też zainstalować w miejscach opisanych w readme, ale osobiście polecam pierwszą metodę.

Moje rozwiązanie dla tego issue jest w tym commicie:
https://github.com/rkubosz/dyplompwr/commit/70b588a1cc6f13dcf946c03ab26f209013228e66
