### ISSUE TITLE
Po zmianie na polski + engineer brak polskich znaków w tytule

### ISSUE THREAD

**Issue by tugot17** [rkubosz/dyplompwr#4]
Przy ustawieniu `\documentclass[engineer,oneside,pl]{resources/dyplompwr}`. Zamiast "Praca Inżynierska" pojawia się "Praca Inynierska" (brak "ż"). Jakby język doczytwał dopiero później, pewnie trzeba jakoś plik `dyplompwr.cls` zmodyfikować ale nie bardzo wiem jak. 

Środowisko: overleaf
Kompilator: LuaLatex

**Comment by rkubosz** [comment]
Naprawiono w commicie 0d91756
